[types]
plain-text      = "Sublime Text"
unix-executable = "Sublime Text"
sourcecode      = "Sublime Text"
yaml            = "Sublime Text"
markdown        = "Sublime Text"
shell           = "Sublime Text"
svg             = "Sublime Text"
quicktime-movie = "IINA"
movie           = "IINA"

[extensions]
mp4  = "IINA"
avi  = "IINA"
json = "Sublime Text"
csv  = "Sublime Text"

[schemes]
web = "Helium"
